trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK $(DOTNET_SDK_VERSION)'
  inputs:
    version: '$(DOTNET_SDK_VERSION)'

- task: PowerShell@2
  displayName: 'Execute Cake PowerShell Bootstrapper'
  inputs:
    filePath: build.ps1

- task: CopyFiles@2
  displayName: 'Copy generated content'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/artifacts'
    contents: '**'
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish API'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/TrackerApi.zip'
    ArtifactName: ApiDrop

- task: PublishBuildArtifacts@1
  displayName: 'Publish Client'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/TrackerClient.zip'
    ArtifactName: ClientDrop