version: '3.9'

services:
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA:?err}
    ports:
      - "1433:1433"
    volumes:
      - ${DATAPATH:?err}\SQL_Data:/var/opt/mssql/data
      - ${DATAPATH:?err}\SQL_Log:/var/opt/mssql/log
      - ${DATAPATH:?err}\SQL_Secrets:/var/opt/mssql/secrets
  redis:
    image: redis:latest
    ports:
      - "6379:6379"